credentials:
  usernames:
    max:
      name: Max Mustermann
      password: '$2a$12$Rxz6FXub7bKRhYwXMZMjlOCj.Q1/yR43cFHyxSDJ1MEP93n0mFmxq'

cookie:
  name: kunden_tool
  key: abcdef123456
  expiry_days: 30

preauthorized:
  emails:
    - max@example.com
