credentials:
  usernames:
    max:
      name: Max Mustermann
      password: '$2b$12$97ESGxRxrplczV3R5T/k0OnUd95SV88OEcAFBLiEG0V.YunH5nF7e'
    lisa:
      name: Lisa Müller
      password: '$2b$12$hULvR4.6rFt9LZqNwex8ieGbPboR5bYduEZiXe0j7XY6D.4ESQulW'

cookie:
  name: kunden_tool
  key: abcdef123456
  expiry_days: 30

preauthorized:
  emails:
    - max@example.com
    - lisa@example.com
